---

# Top-level playbook which includes others needed to build ART + externals

- hosts: all

- include: products/gmp.yml
- include: products/mpfr.yml
- include: products/mpc.yml
- include: products/isl.yml
- include: products/ppl.yml
- include: products/cloog.yml
- include: products/gcc.yml


  
  