---
# Tasks to run autoconf's configure and maybe first a bootrap script to make it.

- name: chirp configure
  debug: msg="configure $pkg in $pkg_build_dir with $configure_opts in $pkg_source_dir and $qualifiers"
  tags:
    - configure

- name: maybe run a bootstrap script for package $pkg
  command: $bootstrap chdir=$pkg_source_dir creates=configure
  when_set: $bootstrap
  tags:
    - configure

- name: run configure for package $pkg
  environment: $configure_env    
  autoconf: chdir=${pkg_build_dir} 
            configure=${pkg_source_dir}/configure
            creates=config.status
            prefix=${pkg_install_dir}
            opts="$configure_opts"
            qualifiers=$qualifiers
  tags:
    - configure
