---

- name: assure build directory for package $pkg
  file: state=directory path=$pkg_build_dir
  when_set: $pkg_build_dir
  tags:
    - directories

- name: assure install directory for package $pkg
  file: state=directory path=$pkg_install_dir
  when_set: $pkg_install_dir
  tags:
    - directories

- name: assure tarball_cache
  file: state=directory path=$tarball_cache
  when_set: $tarball_cache
  tags:
    - directories

- name: assure source_cache
  file: state=directory path=$source_cache
  when_set: $source_cache
  tags:
    - directories
