---

- file: state=directory path=$pkg_build_dir
  when_set: $pkg_build_dir
  tags:
    - directories

- file: state=directory path=$pkg_install_dir
  when_set: $pkg_install_dir
  tags:
    - directories

- file: state=directory path=$tarball_cache
  when_set: $tarball_cache
  tags:
    - directories

- file: state=directory path=$source_cache
  when_set: $source_cache
  tags:
    - directories
