---
# Need to pass in "makes" and "installs" variables


- debug: msg="Using make_env=$make_env"
  tags:
    - install

- name: Run the make command in the build directory of package ${pkg}
  command: make $make_target chdir="${pkg_build_dir}" creates="${pkg_build_dir}/${makes}"
  environment: $make_env    
  when_set: $makes
  tags:
    - install

- name: Run the make install command in the build directory of package ${pkg}
  command: make install chdir="${pkg_build_dir}" creates="${pkg_install_dir}/${installs}"
  environment: $make_env    
  when_set: $installs
  tags:
    - install
