---
# Un-tar a file

- name: untar package $pkg with opts $tar_opts
  command: tar ${tar_opts} ${tar_file} chdir=${pkg_temp_dir} creates=${pkg_source_dir}
  when_set: ${products.${pkg}}
  tags:
    - untar
