---
# Build boost

- hosts: all

  vars:
    pkg: boost
    boost_underscore_version: ${boost_underversion_return.stdout}
    #srcdir: ${pkg}-${version}
    srcdir: ${pkg}_${boost_underscore_version}
    tarball: ${srcdir}.tar.gz
    url: http://downloads.sourceforge.net/project/boost/boost/${version}/$tarball


  tasks:

    - local_action: shell echo $version | tr '.' '_'
      register: boost_underversion_return
      tags:
        - download
        - untar
        - configure

    - include: $top/tasks/directories.yml 

    - include: $top/tasks/download.yml

    - include: $top/tasks/untar.yml tar_opts=-xzf

    # according to the boost installation instructions we need to use
    # cmake here if we don't use the system compiler

    # boost does not use autoconf

    - name: run a bootstrap script for package $pkg
      command: ./bootstrap.sh --prefix=$pkg_install_dir --without-icu --without-libraries=python,mpi chdir=$pkg_source_dir creates=b2
      when_set: $bootstrap
      tags:
        - configure


    # boost doesn't use make

    - name: build and install package $pkg
      command: ./b2 install chdir=$pkg_source_dir creates=include/boost/any.hpp
      tags:
        - install

#    - include: $top/tasks/make.yml installs=something/in/boost/area

  