---
# A playbook to build CLooG

- hosts: all
  vars:
    pkg: cloog
    srcdir: ${pkg}-${version}
    tarball: ${srcdir}.tar.gz
    url: ftp://gcc.gnu.org/pub/gcc/infrastructure/$tarball

  tasks:
    
    - include: $top/tasks/directories.yml

    - include: $top/tasks/download.yml

    - include: $top/tasks/untar.yml tar_opts=-xzf

    - include: $top/tasks/configure.yml 
      vars:
        gmp_prefix: $TEMPLATE($top/templates/pkg_install_dir.j2 {"pkg":"gmp"})
        ppl_prefix: $TEMPLATE($top/templates/pkg_install_dir.j2 {"pkg":"ppl"})
        opts: "--with-gmp-dir=${gmp_prefix} --with-ppl=${ppl_prefix}"

    - include: $top/tasks/make.yml installs=libcloog.a

