---
# Tasks to run autoconf's configure

- name: chirp configure
  debug: msg="configure $pkg in $source_path"
  tags:
    - configure

- name: maybe run autogen in package $pkg in $source_path
  command: ./autogen.sh chdir="${source_path}" creates=configure
  when_string: $run_autogen == 'yes'
  tags:
    - configure

- name: maybe run configure in package $pkg in $source_path
  command: ./configure --prefix=${install_path} ${products.${pkg}.configure_opts}
           chdir=${source_path} creates=config.status
  tags:
    - configure
