---
# A playbook to build cppunit

- hosts: all
  vars:
    pkg: cppunit
    srcdir: ${pkg}-${version}
    tarball: ${srcdir}.tar.gz
    url: http://cgit.freedesktop.org/libreoffice/${pkg}/snapshot/${tarball}

  tasks:
    
    - include: directories.yml

    - include: download.yml

    - include: untar.yml tar_opts=-xzf

    - include: configure.yml bootstrap=./autogen.sh

    - include: make.yml installs=lib/libcppunit.a

