---
# A playbook to build isl

- hosts: all
  vars:
    pkg: isl
    srcdir: ${pkg}-${version}
    tarball: ${srcdir}.tar.bz2
    url: ftp://gcc.gnu.org/pub/gcc/infrastructure/$tarball

    # Override to place along with GCC
    pkg_install_dir: $TEMPLATE($top/templates/pkg_install_dir.j2 {"pkg":"gcc"})

    # null this out so configure uses defaults
    qualifiers: ""
    configure_env: ""
    make_env: ""

  tasks:
    
    - include: $top/tasks/directories.yml

    - include: $top/tasks/download.yml

    - include: $top/tasks/untar.yml tar_opts=-xjf

    - include: $top/tasks/configure.yml 
      vars:
        configure_opts: "--with-gmp-prefix=${pkg_install_dir}"

    - include: $top/tasks/make.yml installs=lib/libisl.a

