---
# A playbook to build mpc

- hosts: all
  vars:
    pkg: mpc
    srcdir: ${pkg}-${version}
    tarball: ${srcdir}.tar.gz
    url: http://www.multiprecision.org/mpc/download/${tarball}

  tasks:
    
    - include: $top/tasks/directories.yml

    - include: $top/tasks/download.yml

    - include: $top/tasks/untar.yml tar_opts=-xzf

    - include: $top/tasks/configure.yml

    - include: $top/tasks/make.yml

