---
# Build PPL (for GCC)
# http://stackoverflow.com/questions/13577436/gcc-4-7-2-requires-ppl

- hosts: all
  vars:
    pkg: ppl
    srcdir: ${pkg}-${version}
    tarball: ${srcdir}.tar.bz2
    url: http://bugseng.com/products/ppl/download/ftp/releases/${version}/$tarball

    # override
    qualifiers: ""

    # Override to place along with GCC
    pkg_install_dir: $TEMPLATE($top/templates/pkg_install_dir.j2 {"pkg":"gcc"})


  tasks:
    
    - include: $top/tasks/directories.yml 

    - include: $top/tasks/download.yml

    - include: $top/tasks/untar.yml tar_opts=-xjf

    - include: $top/tasks/configure.yml 
      vars:
        gmp_prefix: $TEMPLATE($top/templates/pkg_install_dir.j2 {"pkg":"gmp"})
        configure_opts: "--with-out-java --with-gmp=${gmp_prefix}"

    - include: $top/tasks/make.yml installs=lib/libppl.a




