---
# A playbook to build python

- hosts: all
  vars:
    pkg: python
    srcdir: Python-${version}
    tarball: ${srcdir}.tar.bz2
    url: http://www.python.org/ftp/python/${version}/${tarball}

  tasks:
    
    - include: directories.yml

    - include: download.yml 

    - include: untar.yml tar_opts=-xjf

    - include: configure.yml

    - include: make.yml installs=bin/python

